services:
  postgres:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "rinha"
    volumes:
      - "./docker/init.sql:/docker-entrypoint-initdb.d/init.sql"
